// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJdAAnVDe_bCj4l7qXdPkDLGzZjdyd0Cw',
    appId: '1:624484673774:web:94b7c6fc6ed711012c2bff',
    messagingSenderId: '624484673774',
    projectId: 'mother-fetal-ecg',
    authDomain: 'mother-fetal-ecg.firebaseapp.com',
    databaseURL: 'https://mother-fetal-ecg-default-rtdb.firebaseio.com',
    storageBucket: 'mother-fetal-ecg.appspot.com',
    measurementId: 'G-DNXRXMPMRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbMEmdGeiYkFwsBNwS5GPB0CRpJrYIMU',
    appId: '1:624484673774:android:d01285d1317e679c2c2bff',
    messagingSenderId: '624484673774',
    projectId: 'mother-fetal-ecg',
    databaseURL: 'https://mother-fetal-ecg-default-rtdb.firebaseio.com',
    storageBucket: 'mother-fetal-ecg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCieU1l3QOU-uC55H1b14QdSHWTLYXiCCQ',
    appId: '1:624484673774:ios:757073c8b7c5be542c2bff',
    messagingSenderId: '624484673774',
    projectId: 'mother-fetal-ecg',
    databaseURL: 'https://mother-fetal-ecg-default-rtdb.firebaseio.com',
    storageBucket: 'mother-fetal-ecg.appspot.com',
    iosClientId: '624484673774-0fs0g5p0otok6ge27bcu189q528jka64.apps.googleusercontent.com',
    iosBundleId: 'com.example.motherFetalEcg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCieU1l3QOU-uC55H1b14QdSHWTLYXiCCQ',
    appId: '1:624484673774:ios:757073c8b7c5be542c2bff',
    messagingSenderId: '624484673774',
    projectId: 'mother-fetal-ecg',
    databaseURL: 'https://mother-fetal-ecg-default-rtdb.firebaseio.com',
    storageBucket: 'mother-fetal-ecg.appspot.com',
    iosClientId: '624484673774-0fs0g5p0otok6ge27bcu189q528jka64.apps.googleusercontent.com',
    iosBundleId: 'com.example.motherFetalEcg',
  );
}
